# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: mkdir output
#       - name: Read CHANGELOG.MD
#         id: changelog
#         uses: juliangruber/read-file-action@v1
#         with:
#           path: ./CHANGELOG.md
      
      # Runs a single command using the runners shell
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --metadata title="Changelog"
            --output=CHANGELOG.html
            CHANGELOG.md
      
#       - name: move to dir # Move the generated files into output folder
#         run: |
#           mkdir -p output
#           yes| cp -rf testfile.txt ./output/
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action test"
          git add ./output/CHANGELOG.html
          git commit -m "Update CHANGELOG HTML File"
      
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
